# Generated by Django 5.2.3 on 2025-07-14 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vucem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario', models.CharField(help_text='Usuario de VUCEM', max_length=100, unique=True)),
                ('password', models.CharField(help_text='Contraseña de VUCEM', max_length=100)),
                ('patente', models.CharField(help_text='Patente de VUCEM', max_length=100, unique=True)),
                ('is_importador', models.BooleanField(default=False, help_text='Indica si es importador')),
                ('acusecove', models.BooleanField(default=False, help_text='Indica si generara acusecove')),
                ('acuseedocument', models.BooleanField(default=False, help_text='Indica si generara acusee edocumento')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización del registro')),
                ('created_by', models.ForeignKey(help_text='Usuario que creó el VUCEM', on_delete=django.db.models.deletion.CASCADE, related_name='vucems_created', to=settings.AUTH_USER_MODEL)),
                ('organizacion', models.ForeignKey(help_text='Organización a la que pertenece el VUCEM', on_delete=django.db.models.deletion.CASCADE, related_name='vucems', to='organization.organizacion')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuario que actualizó el VUCEM', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vucems_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VUCEM',
                'verbose_name_plural': 'VUCEMs',
                'db_table': 'vucem',
            },
        ),
    ]
