# Generated by Django 5.2.3 on 2025-07-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vucem', '0002_vucem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vucem',
            name='user',
        ),
    ]
