# Generated by Django 5.2.3 on 2025-07-14 17:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vucem', '0003_remove_vucem_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioImportador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rfc', models.CharField(help_text='RFC del usuario importador', max_length=13, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización del registro')),
                ('user', models.ForeignKey(help_text='Usuario de la plataforma asociado al importador', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_importadores', to=settings.AUTH_USER_MODEL)),
                ('vucem', models.ForeignKey(help_text='VUCEM asociado al usuario importador', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_importadores', to='vucem.vucem')),
            ],
            options={
                'verbose_name': 'Usuario Importador',
                'verbose_name_plural': 'Usuarios Importadores',
                'db_table': 'usuario_importador',
            },
        ),
    ]
