# Generated by Django 5.2.3 on 2025-07-14 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_organizacion_membretado_and_more'),
        ('vucem', '0004_usuarioimportador'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioimportador',
            name='organizacion',
            field=models.ForeignKey(blank=True, help_text='Organización a la que pertenece el usuario importador', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_importadores', to='organization.organizacion'),
        ),
    ]
