# Generated by Django 5.2.3 on 2025-07-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vucem', '0005_usuarioimportador_organizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vucem',
            name='cer',
            field=models.FileField(default='', help_text='Certificado de VUCEM', upload_to='vucem_certs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vucem',
            name='key',
            field=models.FileField(default='', help_text='Llave privada de VUCEM', upload_to='vucem_keys/'),
            preserve_default=False,
        ),
    ]
