# Generated by Django 5.2.3 on 2025-07-14 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Tipo de notificación', max_length=100, unique=True)),
                ('descripcion', models.CharField(help_text='Descripción del tipo de notificación', max_length=200)),
            ],
            options={
                'verbose_name': 'Tipo de Notificación',
                'verbose_name_plural': 'Tipos de Notificación',
                'db_table': 'tipo_notificacion',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(help_text='Mensaje de la notificación')),
                ('fecha_envio', models.DateTimeField(blank=True, help_text='Fecha de envío de la notificación', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la notificación')),
                ('visto', models.BooleanField(default=False, help_text='Indica si la notificación ha sido vista')),
                ('dirigido', models.ForeignKey(help_text='Usuario al que se dirige la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(help_text='Tipo de notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='notificaciones.tiponotificacion')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
