# Generated by Django 5.2.3 on 2025-07-14 16:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_agente_aduanal', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=25)),
                ('titular', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=25)),
                ('estado', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('membretado', models.ImageField(blank=True, null=True, upload_to='membretado/')),
                ('membretado_2', models.ImageField(blank=True, null=True, upload_to='membretado/')),
                ('licencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizaciones', to='licence.licencia')),
            ],
            options={
                'verbose_name': 'Organizacion',
                'verbose_name_plural': 'Organizaciones',
                'db_table': 'organizacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsoAlmacenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espacio_utilizado', models.PositiveBigIntegerField(default=0)),
                ('organizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.organizacion')),
            ],
            options={
                'verbose_name': 'Uso de Almacenamiento',
                'verbose_name_plural': 'Usos de Almacenamiento',
                'db_table': 'uso_almacenamiento',
            },
        ),
    ]
