# Generated by Django 5.2.3 on 2025-07-14 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacion',
            name='membretado',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='membretado_2',
        ),
        migrations.CreateModel(
            name='OrganizacionConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membretado', models.ImageField(blank=True, null=True, upload_to='membretado/')),
                ('membretado_2', models.ImageField(blank=True, null=True, upload_to='membretado/')),
                ('organizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='organization.organizacion')),
            ],
            options={
                'verbose_name': 'Configuración de Organización',
                'verbose_name_plural': 'Configuraciones de Organizaciones',
                'db_table': 'organizacion_configuracion',
            },
        ),
    ]
