# Generated by Django 5.2.3 on 2025-06-25 14:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aduana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Aduana',
                'verbose_name_plural': 'Aduanas',
                'db_table': 'aduana',
                'ordering': ['seccion'],
            },
        ),
        migrations.CreateModel(
            name='ClavePedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Clave de Pedimento',
                'verbose_name_plural': 'Claves de Pedimento',
                'db_table': 'clave_pedimento',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='EstadoDeProcesamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estado de Procesamiento',
                'verbose_name_plural': 'Estados de Procesamiento',
                'db_table': 'estado_de_procesamiento',
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='Patente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Patente',
                'verbose_name_plural': 'Patentes',
                'db_table': 'patente',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Regimen',
                'verbose_name_plural': 'Regimenes',
                'db_table': 'regimen',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, max_length=50, null=True)),
                ('hora_fin', models.TimeField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicio',
                'ordering': ['endpoint'],
            },
        ),
        migrations.CreateModel(
            name='TipoDeProcesamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Procesamiento',
                'verbose_name_plural': 'Tipos de Procesamiento',
                'db_table': 'tipo_de_procesamiento',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='TipoOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tipo de Operacion',
                'verbose_name_plural': 'Tipos de Operacion',
                'db_table': 'tipo_operacion',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='AgenteAduanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_aduana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentes_aduanales', to='customs.aduana')),
                ('id_patente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentes_aduanales', to='customs.patente')),
            ],
            options={
                'verbose_name': 'Agente Aduanal',
                'verbose_name_plural': 'Agentes Aduanales',
                'db_table': 'agente_aduanal',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pedimento', models.CharField(help_text='Número de pedimento aduanal', max_length=20, unique=True)),
                ('patente', models.CharField(blank=True, help_text='Número de patente aduanal', max_length=20, null=True)),
                ('aduana', models.CharField(blank=True, help_text='Clave de la aduana según la clasificación aduanera', max_length=10, null=True)),
                ('regimen', models.CharField(blank=True, help_text='Clave del régimen aduanero según la clasificación aduanera', max_length=10, null=True)),
                ('tipo_operacion', models.BooleanField(default=False, help_text='Indica si es una operación de 1 (importación) o 0 (exportación)')),
                ('clave_pedimento', models.CharField(blank=True, help_text='Clave del pedimento según la clasificación aduanera', max_length=10, null=True)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del pedimento')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin del pedimento')),
                ('fecha_pago', models.DateField(blank=True, help_text='Fecha de pago del pedimento', null=True)),
                ('alerta', models.BooleanField(default=False, help_text='Indica si el pedimento tiene una alerta asociada')),
                ('contribuyente', models.CharField(blank=True, help_text='Nombre del contribuyente/importador asociado al pedimento', max_length=100, null=True)),
                ('agente_aduanal', models.CharField(blank=True, help_text='RFC del agente aduanal', max_length=100, null=True)),
                ('curp_apoderado', models.CharField(blank=True, help_text='CURP del apoderado aduanal', max_length=18, null=True)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_disponible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_pedimento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('existe_expediente', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización del registro')),
                ('organizacion', models.ForeignKey(help_text='Organización a la que pertenece el pedimento', on_delete=django.db.models.deletion.CASCADE, related_name='pedimentos', to='organization.organizacion')),
            ],
            options={
                'verbose_name': 'Pedimento',
                'verbose_name_plural': 'Pedimentos',
                'db_table': 'pedimento',
                'ordering': ['pedimento'],
            },
        ),
        migrations.CreateModel(
            name='ProcesamientoPedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesamientos', to='customs.estadodeprocesamiento')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesamientos', to='organization.organizacion')),
                ('pedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesamientos', to='customs.pedimento')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procesamientos', to='customs.servicio')),
                ('tipo_procesamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procesamientos', to='customs.tipodeprocesamiento')),
            ],
            options={
                'verbose_name': 'Procesamiento de Pedimento',
                'verbose_name_plural': 'Procesamientos de Pedimento',
                'db_table': 'procesamiento_pedimento',
                'ordering': ['created_at'],
            },
        ),
    ]
