# Generated by Django 5.2.3 on 2025-07-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenteaduanal',
            name='id_aduana',
        ),
        migrations.RemoveField(
            model_name='agenteaduanal',
            name='id_patente',
        ),
        migrations.DeleteModel(
            name='ClavePedimento',
        ),
        migrations.DeleteModel(
            name='Regimen',
        ),
        migrations.DeleteModel(
            name='Aduana',
        ),
        migrations.DeleteModel(
            name='AgenteAduanal',
        ),
        migrations.DeleteModel(
            name='Patente',
        ),
    ]
