# Generated by Django 5.2.3 on 2025-07-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedimento',
            name='numero_operacion',
            field=models.CharField(blank=True, help_text='Número de operación del pedimento', max_length=20, null=True),
        ),
    ]
