# Generated by Django 5.2.3 on 2025-07-23 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0002_remove_agenteaduanal_id_aduana_and_more'),
        ('organization', '0002_remove_organizacion_membretado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cove', models.CharField(help_text='Número único de la cove', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la cove')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización de la cove')),
                ('organizacion', models.ForeignKey(help_text='Organización a la que pertenece la cove', on_delete=django.db.models.deletion.CASCADE, related_name='coves', to='organization.organizacion')),
                ('pedimento', models.ForeignKey(help_text='Pedimento asociado a la cove', on_delete=django.db.models.deletion.CASCADE, related_name='coves', to='customs.pedimento')),
            ],
            options={
                'verbose_name': 'Cove',
                'verbose_name_plural': 'Coves',
                'db_table': 'coves',
                'ordering': ['created_at'],
            },
        ),
    ]
