# Generated by Django 5.2.3 on 2025-07-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0002_pedimento_numero_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedimento',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Fecha de fin del pedimento', null=True),
        ),
        migrations.AlterField(
            model_name='pedimento',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha de inicio del pedimento', null=True),
        ),
    ]
