# Generated by Django 5.2.3 on 2025-07-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0003_alter_pedimento_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedimento',
            name='importe_pedimento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Importe del pedimento', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pedimento',
            name='importe_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Importe total del pedimento', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pedimento',
            name='saldo_disponible',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Saldo disponible del pedimento', max_digits=10, null=True),
        ),
    ]
