# Generated by Django 5.2.3 on 2025-07-09 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0004_alter_pedimento_importe_pedimento_and_more'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_edocument', models.CharField(help_text='Número único del e-documento', max_length=20, unique=True)),
                ('clave', models.CharField(blank=True, help_text='Clave del e-documento según la clasificación aduanera', max_length=10, null=True)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción del documento', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del documento')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización del documento')),
                ('organizacion', models.ForeignKey(help_text='Organización a la que pertenece el documento', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='organization.organizacion')),
                ('pedimento', models.ForeignKey(help_text='Pedimento asociado al documento', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='customs.pedimento')),
            ],
            options={
                'verbose_name': 'EDocument',
                'verbose_name_plural': 'EDocuments',
                'db_table': 'edocs',
                'ordering': ['created_at'],
            },
        ),
    ]
