# Generated by Django 5.2.3 on 2025-07-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0005_edocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedimento',
            name='numero_operacion',
        ),
        migrations.AddField(
            model_name='pedimento',
            name='numero_partidas',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Número de partidas asociadas al pedimento', null=True),
        ),
        migrations.AddField(
            model_name='pedimento',
            name='remesas',
            field=models.BooleanField(default=False, help_text='Indica si el pedimento tiene remesas asociadas'),
        ),
    ]
