# Generated by Django 5.2.3 on 2025-07-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0006_remove_pedimento_numero_operacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedimento',
            name='numero_operacion',
            field=models.CharField(blank=True, help_text='Número de operación del pedimento', max_length=20, null=True),
        ),
    ]
