# Generated by Django 5.2.3 on 2025-07-09 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0007_pedimento_numero_operacion'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edocument',
            name='organizacion',
            field=models.ForeignKey(help_text='Organización a la que pertenece el edocument', on_delete=django.db.models.deletion.CASCADE, related_name='EDocuments', to='organization.organizacion'),
        ),
    ]
