# Generated by Django 5.2.3 on 2025-07-09 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0008_alter_edocument_organizacion'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edocument',
            name='organizacion',
            field=models.ForeignKey(help_text='Organización a la que pertenece el EDocument', on_delete=django.db.models.deletion.CASCADE, related_name='EDocument', to='organization.organizacion'),
        ),
    ]
